PHP Warnings in Typo3 11 with PHP 8
georgringer/news pull request #1631
Opened 2021-10-30 16:36 UTC by SSFGizmo

https://github.com/georgringer/news/issues/1630

2021-10-31 08:00 UTC, brotkrueml requested changes

2021-10-31 08:00 UTC, brotkrueml commented on Classes/Controller/AdministrationController.php
> +        //if (!$tableRendering) {
Why commented out?

2021-10-31 10:10 UTC, SSFGizmo commented on Classes/Backend/RecordList/NewsDatabaseRecordList.php
> +        //if ($this->thumbs) {
https://github.com/georgringer/news/issues/1630

2021-11-05 08:51 UTC, brotkrueml commented on Classes/Backend/RecordList/NewsDatabaseRecordList.php
> +        $versionInformation = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Information\Typo3Version::class);
No need to use GU, just `(new \TYPO3\CMS\Core\Information\Typo3Version())->getMajorVersion()` as this isn't a service.

2021-11-05 08:51 UTC, brotkrueml commented on Classes/Controller/AdministrationController.php
> +        $versionInformation = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Information\Typo3Version::class);
No need to use GU, just `(new \TYPO3\CMS\Core\Information\Typo3Version())->getMajorVersion()` as this isn't a service.

2022-02-02 12:23 UTC, georgringer commented
this has been now all fixed, therefore closing this PR

2022-02-02 12:23 UTC, closed without merging