[BUGFIX] PHP v8 compatibility
georgringer/news pull request #1691
Opened 2021-12-27 14:13 UTC by mabolek

And a little bit of cleaning.

2022-01-23 09:58 UTC, georgringer approved these changes

2022-01-23 09:58 UTC, georgringer commented
wanna take care of the conflict @mabolek

2022-01-23 18:22 UTC, mabolek commented
Should be resolved now.

2022-01-25 06:25 UTC, georgringer requested changes

2022-01-25 06:25 UTC, georgringer commented on Classes/Controller/NewsBaseController.php
> +        return null;
must be '' now

2022-02-02 12:22 UTC, georgringer commented
has been resolved today with a different commit, sry not using yours

2022-02-02 12:22 UTC, closed without merging